Server:
  Port: 3000 # 服务端口
  Host: 0.0.0.0
  #  debug release test
  Mode: debug # 运行模式
  Prefix: api/v1 # 统一url前缀
  StaticName: /assets # 静态文件的路径 一般为 static static/dist/index.html
  Static: static/assets # 静态文件目录 一般是vite 打包后的静态文件目录
  IndexHtml: static/dist/index.html
Jwt:
  SigningKey: a37e5383b22eb950d1a3496540ceffcc # 盐值 md5(zzhstarter_gin)
  Issuer: satrter_gin # 签发人
  ExpiresAt: 10 # 过期时间(分钟)
