Server:
  Port: 3000 # 服务端口
  Host: 0.0.0.0
  #  debug release test
  Mode: debug # 运行模式
  Prefix: api/v1 # 统一url前缀
  StaticName: /assets # 静态文件的路径 一般为 static static/dist/index.html
  Static: static/assets # 静态文件目录 一般是vite 打包后的静态文件目录
  IndexHtml: static/dist/index.html
  # 设置这个选项之后 会自动开启https 开发环境下 可以使用 go run main.go -g ssl 生成临时证书(有效期为一年)
  # Https:
  #   certFile: ssl/cert.pem # path
  #   keyFile: ssl/key.pem # path
Jwt:
  SigningKey: a37e5383b22eb950d1a3496540ceffcc # 盐值 md5(zzhstarter_gin)
  Issuer: satrter_gin # 签发人
  ExpiresAt: 10 # 过期时间(分钟)
Captcha:
  Width: 300
  Height: 40
  Length: 4
